name: Shell command

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo string
        run: echo "Hellow Word"
      - name: multiline script
        run: |
          node -v
          npm -v