name: Shell command

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo string
        run: echo "Hellow Word"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python
  runs-powershell-command:
    runs-on: windows-latest
    needs: ["run-shell-command"]
    steps:
      - name: directory powershell
        run: Get-Location
      - name: directory bash
        run: pwd
        shell: bash